#----------------------------------------------------------------------
# This file was generated by D:\Users\david\Documents\python_projects\dock_testing_wxpython\venv\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

ARROW_DN = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACoAAAA3CAYAAAB6i9geAAAABGdBTUEAALGPC/xhBQAAAAFz'
    b'UkdCAK7OHOkAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAD7SURBVGhD7ZjLEcIwDESdNEE5QOVA'
    b'N1AFYCbMCEiMJG/8gX2X+BLpZaVcPFzvBCP702U6+ThsN9NJzzg9m4eiaCiKhqJoKIqGomgo'
    b'ioaiaCiKhqJoKIqGomgoiqYb0WF3PJuvdGoweu6BShMdH6NvWfbp1t/P1GKq0ukl0ZZk310+'
    b'Rt+C7JxDfzsqqZnqUu/FRGvIpnomR19S9luvvndUUiJVTQ9VomvKamtXHb0lALVoiRVIYUoU'
    b'KWutZR49QtZTo+qOWnCJ5qTqfdedqKdhzgdmjd7SOEcy8ts7KtEklZtmBJJoSgQhGYGNfk4I'
    b'JRn5nx2VyASRaYYQwg02NDWYclAqmwAAAABJRU5ErkJggg==')

